version: "2"

services:
  balena-starter-interface:
    build:
      context: ./device-info
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
