# This is the default configuration file. It is not meant to be modified. If you would like to use your own configuration, clone 
# this file in to a `config.yml` file in the root of the project, which will override these defaults. 
########
pages:
  #####
  # A list of pages from ui/src/pages to load and the ui/src/components to show on each one.
  #
  # Example that creates an Environment Variable configuration interface:
  #
  # ----------------------------------------------------------------------------------------------------
  # IndexPage:
  #   frames: 
  #     1: 
  #       components: [SystemEnvConfig]
  #   icon: settings   # The label from Google Material Icons to display in the sidebar: https://fonts.google.com/icons
  #   label: yml_config.environment_variables   # The i18n key from ui/src/i18n/en-US.json to use as sidebar text. Only use `yml_config` keys!
  # ----------------------------------------------------------------------------------------------------
  #
  # All the other sections are removed so you only see the environment variable configuration
  #
  #####
  IndexPage: # This page cannot be removed
    frames:
      1:
        components: [SystemJournalDLogs, ToolsSystemInfo]
    icon: info
    label: yml_config.system_info
styles:
  header:
    visible: true # Whether the header logo should be visible
    language_selector: true # Show the language selector in the header bar
    reboot_icon: false # Show the reboot icon in the header bar
    shutdown_icon: false # Show the shutdown icon in the header bar
    title: System Info
