name: "Deploy python-wifi-connect-ui to balena"

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
    paths:
      - 'python-wifi-connect-ui/**'
      - '.github/workflows/**'

env:
  BALENA_APP: bdi/python-wifi-connect-ui
  YML_PATH: python-wifi-connect-ui

jobs:
  build:
    name: "Deploy-to-Balena"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Update balena.yml
        uses: balena-io-experimental/balena.yml-action@main
        with:
          # Synchronise the GitHub README with the Balena Hub README
          path: ${{ env.YML_PATH }}
          sync_readme: true

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BSI_API_KEY }}
          fleet: ${{ env.BALENA_APP }}
          source: ${{ env.YML_PATH }}
